cfg:
  seed: 2024
  run_name: hmragraph_callback_lr1e-4_use_neigh_mix_26
  out_dir: /home/ymiao/code/output
  data_dir: /home/ymiao/data/MasifLigand/
  test_freq: 5
  epochs: 500
  device: 1
  log_dir: /home/ymiao/code/masifligandtrainlog
  path_model: /home/ymiao/code/masifligandtrainlog/lightning_logs/version_27_hmragraph_callback_lr1e-4_use_neigh_mix_adamW_27/checkpoints/epoch=227-accuracy_balanced/val=0.85.ckpt
  min_batch_size: 2
  lr_scheduler: PolynomialLRWithWarmup
  warmup_epochs: 10
  lr_eta_min: 1.0e-08
  loader:
    num_workers: 10
    batch_size: 16
    pin_memory: false
    prefetch_factor: 2
    shuffle: true
  train:
    save_top_k: 2
    early_stoping_patience: 500
    accumulate_grad_batches: 1
    val_check_interval: 1.0
    check_val_every_n_epoch: 1
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    gradient_clip_val: 1.0
    deterministic: false
    max_steps: -1
    auto_lr_find: false
    log_every_n_steps: 50
    detect_anomaly: false
    overfit_batches: 0
    to_monitor: accuracy_balanced/val
  cfg_surface:
    use_surfaces: true
    use_whole_surfaces: false
    data_dir: /home/ymiao/data/MasifLigand/surf_hmr
    feat_keys: all
    oh_keys: all
    gdf_expand: true
  cfg_graph:
    use_graphs: true
    data_dir: /home/ymiao/data/MasifLigand/agraph
    feat_keys: all
    oh_keys: all
    esm_dir: ../../../data/masif_ligand/esm
    use_esm: false
  cfg_head:
    encoded_dims: 128
    output_dims: 7
  diffusion128|gcn128|concurent:
    name: ProteinEncoder
    instanciate:
      _target_: atomsurf.networks.ProteinEncoderBlock
    kwargs:
      surface_encoder:
        name: DiffusionNetBlockBatch
        instanciate:
          _target_: atomsurf.network_utils.DiffusionNetBlockBatch
        kwargs:
          C_width: 128
          mlp_hidden_dims:
          - 128
          - 128
          dropout: 0.1
          use_bn: true
          init_time: 2.0
          init_std: 2.0
      graph_encoder:
        name: GCNx2Block
        instanciate:
          _target_: atomsurf.network_utils.GCNx2Block
        kwargs:
          dim_in: 128
          hidden_dims: 128
          dim_out: 128
          dropout: 0.1
          use_bn: true
          use_weighted_edge_distance: false
      communication_block:
        name: ConcurrentCommunication
        instanciate:
          _target_: atomsurf.network_utils.ConcurrentCommunication
        kwargs:
          use_bp: true
          pre_s_block: linear
          pre_g_block: linear
          pre_s_dim_in: 128
          pre_s_dim_out: 64
          pre_g_dim_in: 128
          pre_g_dim_out: 64
          use_gat: true
          use_v2: false
          bp_self_loops: false
          bp_fill_value: mean
          bp_s_dim_in: 64
          bp_s_dim_out: 64
          bp_g_dim_in: 64
          bp_g_dim_out: 64
          post_s_block: cat_post_process
          post_g_block: cat_post_process
          post_s_dim_in: 128
          post_s_dim_out: 128
          post_g_dim_in: 128
          post_g_dim_out: 128
          neigh_thresh: 8
          sigma: 2.5
  ChemGeomFeatEncoder:
    name: ChemGeomFeatEncoder
    instanciate:
      _target_: atomsurf.networks.ChemGeomFeatEncoder
    kwargs:
      use_neigh: true
      h_dim: 128
      dropout: 0.1
      num_gdf: 16
      num_signatures: 16
      graph_feat_dim: 44
      surface_feat_dim: 52
  diffusion12|gcn12|concurent:
    name: ProteinEncoder
    instanciate:
      _target_: atomsurf.networks.ProteinEncoderBlock
    kwargs:
      surface_encoder:
        name: DiffusionNetBlockBatch
        instanciate:
          _target_: atomsurf.network_utils.DiffusionNetBlockBatch
        kwargs:
          C_width: 12
          mlp_hidden_dims:
          - 12
          - 12
          dropout: 0.0
          use_bn: true
          init_time: 2.0
          init_std: 2.0
      graph_encoder:
        name: GCNx2Block
        instanciate:
          _target_: atomsurf.network_utils.GCNx2Block
        kwargs:
          dim_in: 12
          hidden_dims: 12
          dim_out: 12
          dropout: 0.0
          use_bn: true
          use_weighted_edge_distance: false
      communication_block:
        name: ConcurrentCommunication
        instanciate:
          _target_: atomsurf.network_utils.ConcurrentCommunication
        kwargs:
          use_bp: true
          pre_s_block: linear
          pre_g_block: linear
          pre_s_dim_in: 12
          pre_s_dim_out: 6
          pre_g_dim_in: 12
          pre_g_dim_out: 6
          use_gat: true
          use_v2: false
          bp_self_loops: false
          bp_fill_value: mean
          bp_s_dim_in: 6
          bp_s_dim_out: 6
          bp_g_dim_in: 6
          bp_g_dim_out: 6
          post_s_block: cat_post_process
          post_g_block: cat_post_process
          post_s_dim_in: 12
          post_s_dim_out: 12
          post_g_dim_in: 12
          post_g_dim_out: 12
          neigh_thresh: 8
          sigma: 2.5
  ChemGeomFeatEncoder12:
    name: ChemGeomFeatEncoder
    instanciate:
      _target_: atomsurf.networks.ChemGeomFeatEncoder
    kwargs:
      use_neigh: false
      h_dim: 12
      dropout: 0.1
      num_gdf: 16
      num_signatures: 16
  encoder:
    name: vanilla
    blocks:
    - name: ChemGeomFeatEncoder
      instanciate:
        _target_: atomsurf.networks.ChemGeomFeatEncoder
      kwargs:
        use_neigh: true
        h_dim: 128
        dropout: 0.1
        num_gdf: 16
        num_signatures: 16
        graph_feat_dim: 44
        surface_feat_dim: 52
    - name: ProteinEncoder
      instanciate:
        _target_: atomsurf.networks.ProteinEncoderBlock
      kwargs:
        surface_encoder:
          name: DiffusionNetBlockBatch
          instanciate:
            _target_: atomsurf.network_utils.DiffusionNetBlockBatch
          kwargs:
            C_width: 128
            mlp_hidden_dims:
            - 128
            - 128
            dropout: 0.1
            use_bn: true
            init_time: 2.0
            init_std: 2.0
        graph_encoder:
          name: GCNx2Block
          instanciate:
            _target_: atomsurf.network_utils.GCNx2Block
          kwargs:
            dim_in: 128
            hidden_dims: 128
            dim_out: 128
            dropout: 0.1
            use_bn: true
            use_weighted_edge_distance: false
        communication_block:
          name: ConcurrentCommunication
          instanciate:
            _target_: atomsurf.network_utils.ConcurrentCommunication
          kwargs:
            use_bp: true
            pre_s_block: linear
            pre_g_block: linear
            pre_s_dim_in: 128
            pre_s_dim_out: 64
            pre_g_dim_in: 128
            pre_g_dim_out: 64
            use_gat: true
            use_v2: false
            bp_self_loops: false
            bp_fill_value: mean
            bp_s_dim_in: 64
            bp_s_dim_out: 64
            bp_g_dim_in: 64
            bp_g_dim_out: 64
            post_s_block: cat_post_process
            post_g_block: cat_post_process
            post_s_dim_in: 128
            post_s_dim_out: 128
            post_g_dim_in: 128
            post_g_dim_out: 128
            neigh_thresh: 8
            sigma: 2.5
    - name: ProteinEncoder
      instanciate:
        _target_: atomsurf.networks.ProteinEncoderBlock
      kwargs:
        surface_encoder:
          name: DiffusionNetBlockBatch
          instanciate:
            _target_: atomsurf.network_utils.DiffusionNetBlockBatch
          kwargs:
            C_width: 128
            mlp_hidden_dims:
            - 128
            - 128
            dropout: 0.1
            use_bn: true
            init_time: 2.0
            init_std: 2.0
        graph_encoder:
          name: GCNx2Block
          instanciate:
            _target_: atomsurf.network_utils.GCNx2Block
          kwargs:
            dim_in: 128
            hidden_dims: 128
            dim_out: 128
            dropout: 0.1
            use_bn: true
            use_weighted_edge_distance: false
        communication_block:
          name: ConcurrentCommunication
          instanciate:
            _target_: atomsurf.network_utils.ConcurrentCommunication
          kwargs:
            use_bp: true
            pre_s_block: linear
            pre_g_block: linear
            pre_s_dim_in: 128
            pre_s_dim_out: 64
            pre_g_dim_in: 128
            pre_g_dim_out: 64
            use_gat: true
            use_v2: false
            bp_self_loops: false
            bp_fill_value: mean
            bp_s_dim_in: 64
            bp_s_dim_out: 64
            bp_g_dim_in: 64
            bp_g_dim_out: 64
            post_s_block: cat_post_process
            post_g_block: cat_post_process
            post_s_dim_in: 128
            post_s_dim_out: 128
            post_g_dim_in: 128
            post_g_dim_out: 128
            neigh_thresh: 8
            sigma: 2.5
    - name: ProteinEncoder
      instanciate:
        _target_: atomsurf.networks.ProteinEncoderBlock
      kwargs:
        surface_encoder:
          name: DiffusionNetBlockBatch
          instanciate:
            _target_: atomsurf.network_utils.DiffusionNetBlockBatch
          kwargs:
            C_width: 128
            mlp_hidden_dims:
            - 128
            - 128
            dropout: 0.1
            use_bn: true
            init_time: 2.0
            init_std: 2.0
        graph_encoder:
          name: GCNx2Block
          instanciate:
            _target_: atomsurf.network_utils.GCNx2Block
          kwargs:
            dim_in: 128
            hidden_dims: 128
            dim_out: 128
            dropout: 0.1
            use_bn: true
            use_weighted_edge_distance: false
        communication_block:
          name: ConcurrentCommunication
          instanciate:
            _target_: atomsurf.network_utils.ConcurrentCommunication
          kwargs:
            use_bp: true
            pre_s_block: linear
            pre_g_block: linear
            pre_s_dim_in: 128
            pre_s_dim_out: 64
            pre_g_dim_in: 128
            pre_g_dim_out: 64
            use_gat: true
            use_v2: false
            bp_self_loops: false
            bp_fill_value: mean
            bp_s_dim_in: 64
            bp_s_dim_out: 64
            bp_g_dim_in: 64
            bp_g_dim_out: 64
            post_s_block: cat_post_process
            post_g_block: cat_post_process
            post_s_dim_in: 128
            post_s_dim_out: 128
            post_g_dim_in: 128
            post_g_dim_out: 128
            neigh_thresh: 8
            sigma: 2.5
    - name: ProteinEncoder
      instanciate:
        _target_: atomsurf.networks.ProteinEncoderBlock
      kwargs:
        surface_encoder:
          name: DiffusionNetBlockBatch
          instanciate:
            _target_: atomsurf.network_utils.DiffusionNetBlockBatch
          kwargs:
            C_width: 128
            mlp_hidden_dims:
            - 128
            - 128
            dropout: 0.1
            use_bn: true
            init_time: 2.0
            init_std: 2.0
        graph_encoder:
          name: GCNx2Block
          instanciate:
            _target_: atomsurf.network_utils.GCNx2Block
          kwargs:
            dim_in: 128
            hidden_dims: 128
            dim_out: 128
            dropout: 0.1
            use_bn: true
            use_weighted_edge_distance: false
        communication_block:
          name: ConcurrentCommunication
          instanciate:
            _target_: atomsurf.network_utils.ConcurrentCommunication
          kwargs:
            use_bp: true
            pre_s_block: linear
            pre_g_block: linear
            pre_s_dim_in: 128
            pre_s_dim_out: 64
            pre_g_dim_in: 128
            pre_g_dim_out: 64
            use_gat: true
            use_v2: false
            bp_self_loops: false
            bp_fill_value: mean
            bp_s_dim_in: 64
            bp_s_dim_out: 64
            bp_g_dim_in: 64
            bp_g_dim_out: 64
            post_s_block: cat_post_process
            post_g_block: cat_post_process
            post_s_dim_in: 128
            post_s_dim_out: 128
            post_g_dim_in: 128
            post_g_dim_out: 128
            neigh_thresh: 8
            sigma: 2.5
  dataset:
    surface:
      use_surfaces: true
      use_whole_surfaces: true
      data_dir: ../../../data/masif_ligand/surf_ours
    graph:
      use_graphs: true
      data_dir: ../../../data/masif_ligand/rgraph
  optimizer:
    name: adam
    lr: 0.0001
    b1: 0.9
    b2: 0.99
    weight_decay: 0
    step_size: 10
    gamma: 0.5
    patience: 5
    factor: 0.5
  scheduler:
    name: ReduceLROnPlateau
    patience: 5
    factor: 0.5
