# HMR like encoder : angles to normals are computed and 16 nearest are sent to vertices
hmr_input_encoder:
  _target_: atomsurf.networks.HMRInputEncoder
  h_dim: ${model_hdim}
  use_neigh: ${input_use_neigh}
  dropout: ${model_dropout}
  num_gdf: 16


bihmr_input_encoder:
  _target_: atomsurf.networks.BiHMRInputEncoder
  h_dim: ${model_hdim}
  dropout: ${model_dropout}
  num_gdf: 16

input_encoder:
  name: InputEncoder
  _target_: atomsurf.networks.InputEncoder
  h_dim: ${model_hdim}
  dropout: ${model_dropout}
  num_gdf: 16
  use_bp: true
  use_gvp: true
  use_knn: ${use_knn}
  gvp_use_angles: ${gvp_use_angles}
  use_normals: ${gvp_use_normal}
  vector_gate: ${gvp_vector_gate}
  n_layers: ${gvp_n_layers}
  neigh_thresh: 8
  sigma: 2.5
