# Surface/graph encoders
diffusion_net:
  _target_: diffusion_net.DiffusionNetBlock
  C_width: ${model_hdim}
  dropout: ${model_dropout}
  use_bn: ${eval:'not ${use_layernorm}'}
  use_layernorm: ${use_layernorm}
  init_time: 2.0  # either null (for constant init) or a float
  init_std: 2.0

gcn_block:
  _target_: atomsurf.network_utils.GCNx2Block
  dim_in: ${model_hdim}
  dim_out: ${model_hdim}
  hidden_dims: ${model_hdim}
  dropout: ${model_dropout}
  use_bn: true
  use_weighted_edge_distance: false

pronet_block:
  _target_: atomsurf.network_utils.ProNet
  level: allatom
  num_blocks: 4
  hidden_channels: ${model_hdim}
  mid_emb: ${eval:'${model_hdim} // 2'}
  num_radial: 6
  num_spherical: 2
  cutoff: 10.0
  max_num_neighbors: 32
  int_emb_layers: 3
  num_pos_emb: 16
  dropout: 0.1
  data_augment_eachlayer: False
  euler_noise: False
  add_seq_emb: False

# Message passing schemes
gat_comm:
  _target_: atomsurf.network_utils.communication.surface_graph_comm.SurfaceGraphCommunication
  s_pre_block: ${linear_halver}
  g_pre_block: ${linear_halver}
  bp_sg_block: ${gat_mp}
  bp_gs_block: ${gat_mp}
  s_post_block: ${cat_post_proc}
  g_post_block: ${cat_post_proc}
  neigh_thresh: 8
  sigma: 2.5

gvp_comm:
  _target_: atomsurf.network_utils.communication.surface_graph_comm.SurfaceGraphCommunication
  s_pre_block: ${linear_halver}
  g_pre_block: ${linear_halver}
  bp_sg_block: ${gvp_mp}
  bp_gs_block: ${gvp_mp}
  s_post_block: ${cat_post_proc}
  g_post_block: ${cat_post_proc}
  neigh_thresh: 8
  sigma: 2.5

bihmr_comm:
  _target_: atomsurf.network_utils.communication.surface_graph_comm.SurfaceGraphCommunication
  s_pre_block: ${linear_halver}
  g_pre_block: ${linear_halver}
  bp_sg_block: ${hmr_mp}
  bp_gs_block: ${hmr_mp}
  s_post_block: ${cat_post_proc}
  g_post_block: ${cat_post_proc}
  neigh_thresh: 8
  sigma: 2.5

# Protein Encoder blocks
diff|gcn|gat:
  _target_: atomsurf.networks.ProteinEncoderBlock
  surface_encoder: ${diffusion_net}
  graph_encoder: ${gcn_block}
  message_passing: ${gat_comm}

gvp:
  _target_: atomsurf.networks.ProteinEncoderBlock
  surface_encoder: ${diffusion_net}
  graph_encoder: ${gcn_block}
  message_passing: ${gvp_comm}

pronet|gvp:
  _target_: atomsurf.networks.ProteinEncoderBlock
  surface_encoder: ${diffusion_net}
  graph_encoder: ${pronet_block}
  message_passing: ${gvp_comm}

pronet|HMRMP:
  _target_: atomsurf.networks.ProteinEncoderBlock
  surface_encoder: ${diffusion_net}
  graph_encoder: ${pronet_block}
  message_passing: ${bihmr_comm}

dmasif_block:
  _target_: atomsurf.network_utils.dMasifWrapper
  dim_in: ${model_hdim}
  dim_out: ${model_hdim}
  argdir: ${dmasif_config}

diffonly:
  _target_: atomsurf.networks.ProteinEncoderBlock
  surface_encoder: ${diffusion_net}
  graph_encoder: None
  message_passing: None

dmasifonly:
  _target_: atomsurf.networks.ProteinEncoderBlock
  surface_encoder: ${dmasif_block}
  graph_encoder: None
  message_passing: None

