model_hdim: 128
model_dropout: 0.1

# HMR like encoder : angles to normals are computed and 16 nearest are sent to vertices
ChemGeomFeatEncoder_noneigh:
  name: ChemGeomFeatEncoder
  instanciate:
    _target_: atomsurf.networks.ChemGeomFeatEncoder
  kwargs:
    h_dim: ${model_hdim}
    use_neigh: False
    dropout: ${model_dropout}
    num_gdf: 16
    num_signatures: 16

ChemGeomFeatEncoder_neigh:
  name: ChemGeomFeatEncoder
  instanciate:
    _target_: atomsurf.networks.ChemGeomFeatEncoder
  kwargs:
    h_dim: ${model_hdim}
    use_neigh: True
    dropout: ${model_dropout}
    num_gdf: 16
    num_signatures: 16


# Message passing based encoder, messages goes both ways

GVPChemGeomFeatEncoder:
  name: HMRChemGeomFeatEncoder
  instanciate:
    _target_: atomsurf.networks.HMRChemGeomFeatEncoder
  kwargs:
    h_dim: ${model_hdim}
    dropout: ${model_dropout}
    num_gdf: 16
    num_signatures: 16
    use_bp: true
    use_gvp: true
    use_knn: false
    neigh_thresh: 8
    sigma: 2.5

GVPChemGeomFeatEncoder_normals:
  name: HMRChemGeomFeatEncoder
  instanciate:
    _target_: atomsurf.networks.HMRChemGeomFeatEncoder
  kwargs:
    h_dim: ${model_hdim}
    dropout: ${model_dropout}
    num_gdf: 16
    num_signatures: 16
    use_bp: true
    use_gvp: true
    use_knn: false
    use_normals: true
    neigh_thresh: 8
    sigma: 2.5

GVPChemGeomFeatEncoder_knn:
  name: HMRChemGeomFeatEncoder
  instanciate:
    _target_: atomsurf.networks.HMRChemGeomFeatEncoder
  kwargs:
    h_dim: ${model_hdim}
    dropout: ${model_dropout}
    num_gdf: 16
    num_signatures: 16
    use_bp: true
    use_gvp: true
    use_knn: true
    use_normals: true
    neigh_thresh: 8
    sigma: 2.5