# These should include small blocks, defined in init_block
# TODO
#    elif name == "skip_connection":
#        return SkipConnectionBlock()
#    elif name == "return_processed":
#        return ReturnProcessedBlock()

identity:
  _target_: atomsurf.network_utils.utils_blocks.IdentityLayer

linear_halver:
  _target_: atomsurf.network_utils.communication.utils_blocks.LinearWrapper
  in_features: ${model_hdim}
  out_features: ${eval:'${model_hdim} // 2'}

no_param_agg:
  _target_: atomsurf.network_utils.communication.utils_blocks.NoParamAggregate
  aggr: add
  add_self_loops: false
  fill_value: mean

cat_post_proc:
  _target_: atomsurf.network_utils.communication.utils_blocks.CatPostProcessBlock
  in_dim: ${model_hdim}
  out_dim: ${model_hdim}

gat_mp:
  _target_: atomsurf.network_utils.communication.utils_blocks.GraphconvWrapper
  dim_in: ${eval:'${model_hdim} // 2'}
  dim_out: ${eval:'${model_hdim} // 2'}
  use_gat: true
  use_v2: false
  add_self_loops: false
  fill_value: "mean"

gvp_mp:
  _target_: atomsurf.network_utils.communication.utils_blocks.GVPWrapper
  dim_in: ${eval:'${model_hdim} // 2'}
  dim_out: ${eval:'${model_hdim} // 2'}
  n_layers: ${gvp_n_layers}
  vector_gate: ${gvp_vector_gate}
  gvp_use_angles: ${gvp_use_angles}
  use_normals: ${gvp_use_normal}

hmr_mp:
  _target_: atomsurf.network_utils.communication.utils_blocks.HMRWrapper
  dim_in: ${eval:'${model_hdim} // 2'}
  dim_out: ${eval:'${model_hdim} // 2'}
  num_gdf: 16
