defaults:
  - model_global_variables
  - blocks_zoo_input
  - blocks_zoo
  - encoder: debug
  - optimizer: adam
  - scheduler: reduce_lr_on_plateau
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

hydra:
  job:
    chdir: False
  searchpath:
    - main/../../shared_conf/

# general params
seed: 2024
run_name: default
data_dir: ../../../data/psr/PSR-split-by-year/split-by-year/data
out_dir: ../../../data/psr/out_dir
test_freq: 5
epochs: 100
device: 0
log_dir: "./"
path_model: "version_x/checkpoints/last.ckpt"
min_batch_size: 2

# loader params
loader:
  num_workers: 0
  batch_size: 32
  pin_memory: False
  prefetch_factor: 2
  shuffle: false

train:
  save_top_k: 2
  early_stoping_patience: 100
  accumulate_grad_batches: 1
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  # gradient clipping
  gradient_clip_val: 1.0
  deterministic: False
  # # epochs and batch_size
  max_steps: -1
  auto_lr_find: False
  log_every_n_steps: 50
  # # detect NaNs
  detect_anomaly: False
  # # debugging
  overfit_batches: 0
  to_monitor: local_r/val

cfg_surface:
  use_surfaces: true
  data_dir: ../../../data/psr/PSR-split-by-year/split-by-year/data
  feat_keys: 'all'
  oh_keys: 'all'

# python train.py 'cfg_graph.feat_keys=[hphobs]' 'cfg_graph.oh_keys=[amino_types]' cfg_graph.use_esm=True
cfg_graph:
  use_graphs: true
  data_dir: ../../../data/psr/PSR-split-by-year/split-by-year/data
  feat_keys: 'all'
  oh_keys: 'all'
  esm_dir: ../../../data/psr/PSR-split-by-year/split-by-year/data
  use_esm: false

cfg_head:
  encoded_dims: ${model_hdim}
  dropout: 0.25
