diffusion128|gcn128|concurent:
  name: ProteinEncoder
  instanciate:
    _target_: atomsurf.networks.ProteinEncoderBlock
  kwargs:
    surface_encoder:
      name: DiffusionNetBlockBatch
      instanciate:
        _target_: atomsurf.network_utils.DiffusionNetBlockBatch  # diffusion_net.DiffusionNet
      kwargs:
        C_width: 128
        mlp_hidden_dims: [128, 128]
        dropout: 0.1
        use_bn: true
        init_time: 2.0  # either null (for constant init) or a float
        init_std: 2.0
    graph_encoder:
      name: GCNx2Block
      instanciate:
        _target_: atomsurf.network_utils.GCNx2Block
      kwargs:
        dim_in: 128
        hidden_dims: 128
        dim_out: 128
        dropout: 0.1
        use_bn: true
        use_weighted_edge_distance: false
    communication_block:
      name: ConcurrentCommunication
      instanciate:
        _target_: atomsurf.network_utils.ConcurrentCommunication
      kwargs:
        use_bp: true
        pre_s_block: linear
        pre_g_block: linear
        pre_s_dim_in: 128
        pre_s_dim_out: 64
        pre_g_dim_in: 128
        pre_g_dim_out: 64

        use_gat: true
        use_v2: false
        bp_self_loops: false
        bp_fill_value: "mean"
        bp_s_dim_in: 64
        bp_s_dim_out: 64
        bp_g_dim_in: 64
        bp_g_dim_out: 64

        post_s_block: cat_post_process
        post_g_block: cat_post_process
        post_s_dim_in: 128
        post_s_dim_out: 128
        post_g_dim_in: 128
        post_g_dim_out: 128

        neigh_thresh: 8
        sigma: 2.5

ChemGeomFeatEncoder:
  name: ChemGeomFeatEncoder
  instanciate:
    _target_: atomsurf.networks.ChemGeomFeatEncoder
  kwargs:
    use_neigh: True #False
    h_dim: 128
    dropout: 0.1
    num_gdf: 16
    num_signatures: 16


diffusion12|gcn12|concurent:
  name: ProteinEncoder
  instanciate:
    _target_: atomsurf.networks.ProteinEncoderBlock
  kwargs:
    surface_encoder:
      name: DiffusionNetBlockBatch
      instanciate:
        _target_: atomsurf.network_utils.DiffusionNetBlockBatch
      kwargs:
        C_width: 12
        mlp_hidden_dims: [12, 12]
        dropout: 0.0
        use_bn: true
        init_time: 2.0  # either null (for constant init) or a float
        init_std: 2.0
    graph_encoder:
      name: GCNx2Block
      instanciate:
        _target_: atomsurf.network_utils.GCNx2Block
      kwargs:
        dim_in: 12
        hidden_dims: 12
        dim_out: 12
        dropout: 0.0
        use_bn: true
        use_weighted_edge_distance: false
    communication_block:
      name: ConcurrentCommunication
      instanciate:
        _target_: atomsurf.network_utils.ConcurrentCommunication
      kwargs:
        use_bp: true
        pre_s_block: linear
        pre_g_block: linear
        pre_s_dim_in: 12
        pre_s_dim_out: 6
        pre_g_dim_in: 12
        pre_g_dim_out: 6

        use_gat: true
        use_v2: false
        bp_self_loops: false
        bp_fill_value: "mean"
        bp_s_dim_in: 6
        bp_s_dim_out: 6
        bp_g_dim_in: 6
        bp_g_dim_out: 6

        post_s_block: cat_post_process
        post_g_block: cat_post_process
        post_s_dim_in: 12
        post_s_dim_out: 12
        post_g_dim_in: 12
        post_g_dim_out: 12

        neigh_thresh: 8
        sigma: 2.5

ChemGeomFeatEncoder12:
  name: ChemGeomFeatEncoder
  instanciate:
    _target_: atomsurf.networks.ChemGeomFeatEncoder
  kwargs:
    use_neigh: False
    h_dim: 12
    dropout: 0.1
    num_gdf: 16
    num_signatures: 16