defaults:
  - _self_
  - blocks_zoo
  - encoder: vanilla #debug
  - dataset: vanilla
  #  - dataset@trainset: [ masif_ligand_hmr ]
  #  - dataset@valset: [ masif_ligand_hmr ]
  #  - dataset@testset: [ masif_ligand_hmr ]
  - optimizer: adam
  - scheduler: reduce_lr_on_plateau
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

#hydra:
#job:
#chdir: False

# general params
seed: 2024
run_name: default
data_dir: /home/ymiao/data/MasifLigand/
out_dir: /home/ymiao/data/out_dir
test_freq: 5
epochs: 400
device: 0
log_dir: "./"
path_model: "version_x/checkpoints/last.ckpt"
lr_scheduler: PolynomialLRWithWarmup
warmup_epochs: 10
lr_eta_min: 1E-8
# loader params
loader:
  num_workers: 20
  batch_size: 32
  pin_memory: False
  prefetch_factor: 2
  shuffle: true

train:
  save_top_k: 2
  early_stoping_patience: 100
  accumulate_grad_batches: 1
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  # gradient clipping
  gradient_clip_val: 1.0
  deterministic: False
  # # epochs and batch_size
  max_steps: -1
  auto_lr_find: False
  log_every_n_steps: 50
  # # detect NaNs
  detect_anomaly: False
  # # debugging
  overfit_batches: 0
  to_monitor: accuracy_balanced/val

cfg_surface:
  use_surfaces: true
  use_whole_surfaces: False
  data_dir: /home/ymiao/data/MasifLigand/surf_ours
  feat_keys: 'all'
  oh_keys: 'all'

# python train.py 'cfg_graph.feat_keys=[hphobs]' 'cfg_graph.oh_keys=[amino_types]' cfg_graph.use_esm=True
cfg_graph:
  use_graphs: true
  data_dir: /home/ymiao/data/MasifLigand/rgraph
  feat_keys: 'all'
  oh_keys: 'all'
  esm_dir: /home/ymiao/data/MasifLigand/esm
  use_esm: false

#cfg_graph:
#  use_graphs: true
#  data_dir: ../../../data/masif_ligand/agraph
#  feat_keys: 'all'
#  oh_keys: 'all'
#  esm_dir: ../../../data/masif_ligand/esm
#  use_esm: false

cfg_head:
  encoded_dims: 128 #12
  output_dims: 7
