defaults:
  - _self_
  - blocks_zoo
  - encoder: vanilla
  - dataset: vanilla
  - optimizer: adam
  - scheduler: polynomial_lr
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:
  job:
    chdir: False
  searchpath:
    - main/../../shared_conf/

# general params
seed: 2024
run_name: default
out_dir: ../../../outputs/masif_site/out_dir # does not work for me with chdir=False
log_dir: "./"
test_freq: 5
epochs: 200
device: 0
path_model: "version_x/checkpoints/last.ckpt"
min_batch_size: 2
use_wandb: False

# loader params
loader:
  num_workers: 2
  batch_size: 16
  pin_memory: False
  prefetch_factor: 2
  shuffle: true

train:
  save_top_k: 2
  early_stoping_patience: 100
  accumulate_grad_batches: 1
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  # gradient clipping
  gradient_clip_val: 1.0
  deterministic: False
  # # epochs and batch_size
  max_steps: -1
  auto_lr_find: False
  log_every_n_steps: 50
  # # detect NaNs
  detect_anomaly: False
  # # debugging
  overfit_batches: 0
  to_monitor: auroc/val

cfg_surface:
  use_surfaces: true
  #  data_dir: ../../../data/masif_site/surfaces
  data_dir: ../../../data/masif_site/surfaces_0.1_False
  feat_keys: 'all'
  oh_keys: 'all'
  gdf_expand: true

# python train.py 'cfg_graph.feat_keys=[hphobs]' 'cfg_graph.oh_keys=[amino_types]' cfg_graph.use_esm=True
cfg_graph:
  use_graphs: true
  data_dir: ../../../data/masif_site/agraph
  #  data_dir: ../../../data/masif_site/rgraph
  feat_keys: 'all'
  oh_keys: 'all'
  esm_dir: ../../../data/masif_site/esm
  use_esm: false


cfg_head:
  encoded_dims: 128
  output_dims: 1
